### ISSUE TITLE
Code is not completed

### ISSUE THREAD

**Issue by cliangyu** [acl21/init-pools-dal#1]
Hi, I failed to run `python simclr.py --config_env configs/env.yml --config_exp configs/pretext/simclr_cifar10.yml`
as there are many discrepancies in the code base.

I guess this is not the latest usable version of the code base. Could you please look into it and push the latest usable code?

**Comment by cliangyu** [comment]
`data` folder was missing, case closed.

https://github.com/wvangansbeke/Unsupervised-Classification/tree/master/data

**Comment by acl21** [comment]
Glad you found the solution. Good luck.
