### ISSUE TITLE
Notebook to draw figure 1

### ISSUE THREAD

**Issue by cliangyu** [acl21/init-pools-dal#2]
https://colab.research.google.com/drive/1kk7kEsiuctrwsNL4WciU1XVM_enJDbD3?usp=sharing

Copied from another issue, if anyone is interested.

Will appreciate authors if you would like to share the plotting code for the Figure 7 & 8 too!

**Comment by acl21** [comment]
Sure. You can find all the plotting code notebooks here: 
1. [Figure 1](https://colab.research.google.com/drive/1kk7kEsiuctrwsNL4WciU1XVM_enJDbD3?usp=sharing)
2. [Main Experiment Results](https://colab.research.google.com/drive/1o5n0BxH2PsJwYluKhovKdN8nmePvZqC8?usp=sharing)
3. [t-SNE and Overlap Statistics](https://colab.research.google.com/drive/1_IzkkdASAl1HZdVP7ht1262MZ9Dno5jD?usp=sharing)

Sorry, the code isn't the best and can be optimized. Good luck! 😄
