### ISSUE TITLE
Active learning procedure and config

### ISSUE THREAD

**Issue by cliangyu** [acl21/init-pools-dal#3]
Hi! 
I have successfully finished all the pre-training and clustering process till the end of selflabel.
May I know about the practices to start active learning cycles?
Including: running files, configs.

**Comment by acl21** [comment]
Hi, I based this codebase on my original AL toolkit and you can find how to run the code files here - https://github.com/acl21/deep-active-learning-pytorch/blob/main/docs/GETTING_STARTED.md. This should answer most of your questions. Also, the toolkit is obviously more latest than this repo so watch out for that. If anything is unclear, please ask here. Good luck!
