### ISSUE TITLE
Variable definition missing

### ISSUE THREAD

**Issue by cliangyu** [acl21/init-pools-dal#5]
https://github.com/acl21/init-pools-dal/blob/main/Unsupervised-Classification/Clustering%20Sample.ipynb

Variable `c_budget` is called before assignment.

**Comment by acl21** [comment]
Yes. This is a mistake. Please replace it with `cluster_budgets[idx]` and you should be good to go.

**Comment by cliangyu** [comment]
Thank you! Solved
