### ISSUE TITLE
Image transform

### ISSUE THREAD

**Issue by cliangyu** [acl21/init-pools-dal#6]
Hi, I got this bug when running Clustering Sample.ipynb, images, labels = dataiter.next()

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_9971/4224299185.py in <module>
----> 1 images, labels = dataiter.next()
      2 
      3 imshow(torchvision.utils.make_grid(images))
      4 print(labels)

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    559     def _next_data(self):
    560         index = self._next_index()  # may raise StopIteration
--> 561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    562         if self._pin_memory:
    563             data = _utils.pin_memory.pin_memory(data)

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

/tmp/ipykernel_9971/923088962.py in __getitem__(self, index)
     72 
     73         if self.transform is not None:
---> 74             img = self.transform(img)
     75 
     76         return img, target

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torchvision/transforms/transforms.py in __call__(self, img)
     92     def __call__(self, img):
     93         for t in self.transforms:
---> 94             img = t(img)
     95         return img
     96 

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1104         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1105                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1106             return forward_call(*input, **kwargs)
   1107         # Do not call functions when jit is used
   1108         full_backward_hooks, non_full_backward_hooks = [], []

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torchvision/transforms/transforms.py in forward(self, img)
    663         """
    664         if self.padding is not None:
--> 665             img = F.pad(img, self.padding, self.fill, self.padding_mode)
    666 
    667         width, height = F.get_image_size(img)

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torchvision/transforms/functional.py in pad(img, padding, fill, padding_mode)
    472     """
    473     if not isinstance(img, torch.Tensor):
--> 474         return F_pil.pad(img, padding=padding, fill=fill, padding_mode=padding_mode)
    475 
    476     return F_t.pad(img, padding=padding, fill=fill, padding_mode=padding_mode)

~/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py in pad(img, padding, fill, padding_mode)
    135 
    136     if not _is_pil_image(img):
--> 137         raise TypeError("img should be PIL Image. Got {}".format(type(img)))
    138 
    139     if not isinstance(padding, (numbers.Number, tuple, list)):

TypeError: img should be PIL Image. Got <class 'numpy.ndarray'>
`

**Comment by acl21** [comment]
Ah! Do not use this notebook. I think you will only need those numbered (1-6) notebooks. This one is just outdated and not useful.

**Comment by cliangyu** [comment]
Thank you for the reminder.
