### ISSUE TITLE
DataParallel Support

### ISSUE THREAD

**Issue by cliangyu** [acl21/init-pools-dal#8]
Is there any particular rationale or technical difficulty of not implementing DataParallel for AL?

**Comment by c-liangyu** [comment]
I am doing CIFAR-10 experiments on a RTX 2080 Ti GPU. It takes 10 hours per episode. Wondering about performance improving techniques.

**Comment by cliangyu** [comment]
Well, as currently we are running on small datatsets, single GPU is fair enough.

**Comment by cliangyu** [comment]
However, the training process is relatively slow. I am checking the performance bottleneck.
